package entities;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.NamedQueries;
import jakarta.persistence.NamedQuery;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * This Customer entity class persists customer details in the CUSTOMER table.
 *
 * The assignment requires customer details and customer orders to be stored in
 * the database. One customer can have many orders (one-to-many), and each order
 * belongs to only one customer.
 *
 * FIX applied: replaced Customer.findByLastName with Customer.findByName using
 * CONCAT to support full-name search as shown in the demo document.
 */
@Entity
@Table(name = "CUSTOMER")
@NamedQueries({
    // Retrieves all customers ordered by name for the customer list page.
    @NamedQuery(name = "Customer.findAll",
            query = "SELECT c FROM Customer c ORDER BY c.lastName, c.firstName"),

    // Finds a single customer by primary key for the customer detail view.
    @NamedQuery(name = "Customer.findById",
            query = "SELECT c FROM Customer c WHERE c.customerId = :customerId"),

    // Finds a customer by email address; used to check for duplicate registration.
    @NamedQuery(name = "Customer.findByEmail",
            query = "SELECT c FROM Customer c WHERE c.email = :email"),

    // Searches customers by full name using LIKE for partial match.
    // This supports the demo page "Search for a Customer" which searches by name.
    @NamedQuery(name = "Customer.findByName",
            query = "SELECT c FROM Customer c WHERE LOWER(CONCAT(c.firstName, ' ', c.lastName)) LIKE LOWER(CONCAT('%', :name, '%'))")
})
public class Customer implements Serializable {

    private static final long serialVersionUID = 1L;

    // Primary key auto-generated by the database identity strategy.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "CUSTOMER_ID")
    private Long customerId;

    // First name of the customer - required.
    @NotBlank(message = "First name is required")
    @Size(max = 100, message = "First name must be less than 100 characters")
    @Column(name = "FIRST_NAME", nullable = false, length = 100)
    private String firstName;

    // Last name of the customer - required.
    @NotBlank(message = "Last name is required")
    @Size(max = 100, message = "Last name must be less than 100 characters")
    @Column(name = "LAST_NAME", nullable = false, length = 100)
    private String lastName;

    // Email address - required and must be unique per customer.
    @NotBlank(message = "Email is required")
    @Email(message = "Please enter a valid email address")
    @Size(max = 150, message = "Email must be less than 150 characters")
    @Column(name = "EMAIL", nullable = false, unique = true, length = 150)
    private String email;

    // Phone number of the customer.
    @Size(max = 30, message = "Phone number must be less than 30 characters")
    @Column(name = "PHONE", length = 30)
    private String phone;

    // Street or delivery address of the customer.
    @Size(max = 300, message = "Address must be less than 300 characters")
    @Column(name = "ADDRESS", length = 300)
    private String address;

    /**
     * One-to-many: one customer can have many orders. mappedBy refers to the
     * 'customer' field in CustomerOrder. CascadeType.ALL propagates
     * persist/merge/remove to child orders. orphanRemoval = true removes orders
     * deleted from this list.
     */
    @OneToMany(mappedBy = "customer", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<CustomerOrder> orders = new ArrayList<>();

    /**
     * No-arg constructor required by JPA.
     */
    public Customer() {
    }

    /**
     * Full constructor for creating a customer with all fields at once.
     *
     * @param firstName customer first name
     * @param lastName customer last name
     * @param email customer email address
     * @param phone customer phone number
     * @param address customer address
     */
    public Customer(String firstName, String lastName, String email,
            String phone, String address) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phone = phone;
        this.address = address;
    }

    /**
     * Returns the combined full name for display in JSF pages.
     *
     * @return first name followed by a space and last name
     */
    public String getFullName() {
        return firstName + " " + lastName;
    }

    /**
     * Bidirectional helper: adds an order and sets the customer reference on
     * it.
     *
     * @param order the order to add to this customer
     */
    public void addOrder(CustomerOrder order) {
        orders.add(order);
        order.setCustomer(this);
    }

    /**
     * Bidirectional helper: removes an order and clears its customer reference.
     *
     * @param order the order to remove from this customer
     */
    public void removeOrder(CustomerOrder order) {
        orders.remove(order);
        order.setCustomer(null);
    }

    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public List<CustomerOrder> getOrders() {
        return orders;
    }

    public void setOrders(List<CustomerOrder> orders) {
        this.orders = orders;
    }
}
